### ISSUE TITLE
On some styles exception is thrown, "Attributes for Style "%s" not found"

### ISSUE THREAD

**Issue by codernov** [EtheaDev/VCLThemeSelector#1]
I'm not a Delphi programmer, so I can not debug this properly. But, I tried your demo, added styles via Project->Options... and I linked VCLThemeSelector into my C++Builder project where I'm loading styles dynamically at runtime, and I get this same error. Attributes for Style "%s" not found..

It does not happen for all styles. If styles loaded or included with projects are alright, everything works. But with some styles it does not work. And there is nothing wrong with styles.. Here is one for you to test with -- [https://www.upload.ee/files/13836455/none-working-style.zip.html]

Why does this happen and what to do about it??

**Comment by codernov** [comment]
I answered my own question. There are declarations for styles under the function that throws exception. Essentially because of this I can not use VCLThemeSelector in my project. I'm going to design my own theme selector. 

P.S. I don't know how you guys use Delphi, it's a horrible language to begin with and it's complicated with your unprofessional programming practices. Essentially a wall of code without any comments.

**Comment by carloBarazzetta** [comment]
Actually the code into InitDefaultThemesAttributes intitialize some common styles using RegisterThemeAttributes, and is called from initialization section of the unit.

I'm adding the option to call RegisterThemeAttributes, so you can add your custom style, for example "MyStyle", like in this example:
```Delphi
RegisterThemeAttributes('MyStyle'   ,ttLight, clWebLightYellow  , clWebLightgrey);
```

**Comment by carloBarazzetta** [comment]
In the last commit I've added the option to call RegisterThemeAttributes
